### PR TITLE
Get current base domain

### PR DESCRIPTION
**Pull request by spoonerWeb**
Additionally outputs the current base domain in exception if not valid.

Closes: #88

### CODE REVIEW

**Comment by einpraegsam** [comment]
Thx, discussion startet here: https://github.com/in2code-de/luxletter/issues/88

**Comment by einpraegsam** [comment]
Wanted to merge it but CS-Fixer test failed. Any interest in fixing this? @spoonerWeb

**Comment by spoonerWeb** [comment]
@einpraegsam Sure, can you re-run the checks as the logs are not existing anymore? 😬

**Comment by einpraegsam** [comment]
Hi Spoony, I don't know how to re-run old tests on any branch. Nevertheless I took over your code and simply pushed it in c494e3404d6854ccbfd3ce6a2c422ab34ea13174

Thx for your time

**Pull request closed without merging**
